Repository meilisearch/milli, pull requests merged in 2021-08, with the labels that each got.

#300 Fix prefix level position docids database
  milli/src/update/words_level_positions.rs
Labels: breaking-change

#302 Update milli to v0.9.0
  helpers/Cargo.toml
  http-ui/Cargo.toml
  infos/Cargo.toml
  milli/Cargo.toml
  search/Cargo.toml
Labels: skip-changelog

#303 Remove max values by facet limit for facet distribution
  milli/src/search/facet/facet_distribution.rs
  milli/src/search/facet/facet_string.rs
Labels: breaking-change

#307 Update version for the next release (v0.10.0)
  helpers/Cargo.toml
  http-ui/Cargo.toml
  infos/Cargo.toml
  milli/Cargo.toml
  search/Cargo.toml
Labels: skip-changelog

#312 Update milli version to v0.10.1
  helpers/Cargo.toml
  http-ui/Cargo.toml
  infos/Cargo.toml
  milli/Cargo.toml
  search/Cargo.toml
Labels: skip-changelog

#309 Sort at query time
  benchmarks/benches/search_songs.rs
  http-ui/src/main.rs
  milli/Cargo.toml
  milli/src/criterion.rs
  milli/src/error.rs
  milli/src/index.rs
  milli/src/lib.rs
  milli/src/search/criteria/asc_desc.rs
  milli/src/search/criteria/mod.rs
  milli/src/search/facet/facet_string.rs
  milli/src/search/mod.rs
  milli/src/update/settings.rs
  milli/tests/assets/test_set.ndjson
  milli/tests/search/distinct.rs
  milli/tests/search/filters.rs
  milli/tests/search/mod.rs
  milli/tests/search/query_criteria.rs
Labels: breaking-change

#317 Fix the facet string docids filterable deletion bug
  milli/src/update/delete_documents.rs
Labels: bug

#319 Update version for the next release (v0.10.2)
  helpers/Cargo.toml
  http-ui/Cargo.toml
  infos/Cargo.toml
  milli/Cargo.toml
  search/Cargo.toml
Labels: skip-changelog

#320 Sort at query time
  benchmarks/benches/search_songs.rs
  http-ui/src/main.rs
  milli/Cargo.toml
  milli/src/criterion.rs
  milli/src/error.rs
  milli/src/index.rs
  milli/src/lib.rs
  milli/src/search/criteria/asc_desc.rs
  milli/src/search/criteria/mod.rs
  milli/src/search/facet/facet_string.rs
  milli/src/search/mod.rs
  milli/src/update/settings.rs
  milli/tests/assets/test_set.ndjson
  milli/tests/search/distinct.rs
  milli/tests/search/filters.rs
  milli/tests/search/mod.rs
  milli/tests/search/query_criteria.rs
Labels: breaking-change

#325 Update milli version to v0.11.0
  helpers/Cargo.toml
  http-ui/Cargo.toml
  http-ui/src/main.rs
  infos/Cargo.toml
  milli/Cargo.toml
  milli/src/lib.rs
  search/Cargo.toml
Labels: skip-changelog
