Repository meilisearch/milli, pull requests merged in 2021-07, with the labels that each got.

#281 Bump to v0.7.2
  Cargo.lock
  helpers/Cargo.toml
  http-ui/Cargo.toml
  infos/Cargo.toml
  milli/Cargo.toml
  search/Cargo.toml
Labels: skip-changelog

#254 Improve the facet string distribution speed
  infos/src/main.rs
  milli/src/heed_codec/facet/facet_level_value_u32_codec.rs
  milli/src/heed_codec/facet/facet_string_level_zero_codec.rs
  milli/src/heed_codec/facet/facet_string_level_zero_value_codec.rs
  milli/src/heed_codec/facet/facet_string_zero_bounds_value_codec.rs
  milli/src/heed_codec/facet/field_doc_id_facet_string_codec.rs
  milli/src/heed_codec/facet/mod.rs
  milli/src/index.rs
  milli/src/search/criteria/asc_desc.rs
  milli/src/search/distinct/facet_distinct.rs
  milli/src/search/distinct/mod.rs
  milli/src/search/facet/facet_distribution.rs
  milli/src/search/facet/facet_number.rs
  milli/src/search/facet/facet_string.rs
  milli/src/search/facet/filter_condition.rs
  milli/src/search/facet/mod.rs
  milli/src/search/mod.rs
  milli/src/update/delete_documents.rs
  milli/src/update/facets.rs
  milli/src/update/index_documents/merge_function.rs
  milli/src/update/index_documents/mod.rs
  milli/src/update/index_documents/store.rs
  milli/src/update/settings.rs
Labels: enhancement

#291 Fix a bug about zero bytes in the inputs
  Cargo.lock
  milli/Cargo.toml
  milli/src/update/delete_documents.rs
  milli/src/update/index_documents/mod.rs
Labels: bug

#295 Update version for the next release (v0.8.0)
  helpers/Cargo.toml
  http-ui/Cargo.toml
  infos/Cargo.toml
  milli/Cargo.toml
  search/Cargo.toml
Labels: skip-changelog

#296 Fix invalid faceted documents ids buffer size
  milli/src/index.rs
Labels: bug
