Repository meilisearch/milli, pull requests merged in 2021-09, with the labels that each got.

#337 Update version for the next release (v0.12.0)
  helpers/Cargo.toml
  http-ui/Cargo.toml
  infos/Cargo.toml
  milli/Cargo.toml
  search/Cargo.toml
Labels: skip-changelog

#308 Implement a better parallel indexer
  http-ui/src/main.rs
  infos/src/main.rs
  milli/Cargo.toml
  milli/src/heed_codec/facet/facet_string_level_zero_value_codec.rs
  milli/src/heed_codec/facet/mod.rs
  milli/src/heed_codec/roaring_bitmap/cbo_roaring_bitmap_codec.rs
  milli/src/index.rs
  milli/src/lib.rs
  milli/src/proximity.rs
  milli/src/search/criteria/mod.rs
  milli/src/search/facet/facet_string.rs
  milli/src/search/facet/filter_condition.rs
  milli/src/update/delete_documents.rs
  milli/src/update/facets.rs
  milli/src/update/index_documents/extract/extract_docid_word_positions.rs
  milli/src/update/index_documents/extract/extract_facet_number_docids.rs
  milli/src/update/index_documents/extract/extract_facet_string_docids.rs
  milli/src/update/index_documents/extract/extract_fid_docid_facet_values.rs
  milli/src/update/index_documents/extract/extract_fid_word_count_docids.rs
  milli/src/update/index_documents/extract/extract_word_docids.rs
  milli/src/update/index_documents/extract/extract_word_level_position_docids.rs
  milli/src/update/index_documents/extract/extract_word_pair_proximity_docids.rs
  milli/src/update/index_documents/extract/mod.rs
  milli/src/update/index_documents/helpers/clonable_mmap.rs
  milli/src/update/index_documents/helpers/grenad_helpers.rs
  milli/src/update/index_documents/helpers/merge_functions.rs
  milli/src/update/index_documents/helpers/mod.rs
  milli/src/update/index_documents/merge_function.rs
  milli/src/update/index_documents/mod.rs
  milli/src/update/index_documents/store.rs
  milli/src/update/index_documents/transform.rs
  milli/src/update/index_documents/typed_chunk.rs
  milli/src/update/settings.rs
  milli/src/update/update_builder.rs
  milli/src/update/word_prefix_docids.rs
  milli/src/update/word_prefix_pair_proximity_docids.rs
  milli/src/update/words_level_positions.rs
  milli/src/update/words_prefixes_fst.rs
  milli/tests/search/mod.rs
Labels: breaking-change

#341 Throw a query time error when a sort parameter is used but the sort ranking rule is missing
  milli/src/error.rs
  milli/src/search/mod.rs
  milli/tests/search/mod.rs
  milli/tests/search/sort.rs
Labels: breaking-change

#347 Update version for the next release (v0.13.0)
  helpers/Cargo.toml
  http-ui/Cargo.toml
  infos/Cargo.toml
  milli/Cargo.toml
  search/Cargo.toml
Labels: skip-changelog

#349 Enable the grenad tempfile feature back
  http-ui/src/main.rs
  milli/Cargo.toml
Labels: enhancement

#342 Let the caller decide what kind of error they want to returns when parsing `AscDesc`
  milli/src/criterion.rs
  milli/src/error.rs
Labels: breaking-change

#354 Update version for the next release (v0.13.1)
  helpers/Cargo.toml
  http-ui/Cargo.toml
  infos/Cargo.toml
  milli/Cargo.toml
  search/Cargo.toml
Labels: skip-changelog

#322 Geosearch
  http-ui/public/script.js
  http-ui/src/main.rs
  milli/Cargo.toml
  milli/src/criterion.rs
  milli/src/error.rs
  milli/src/index.rs
  milli/src/lib.rs
  milli/src/search/criteria/geo.rs
  milli/src/search/criteria/mod.rs
  milli/src/search/facet/filter_condition.rs
  milli/src/search/facet/grammar.pest
  milli/src/search/mod.rs
  milli/src/update/clear_documents.rs
  milli/src/update/delete_documents.rs
  milli/src/update/index_documents/extract/extract_geo_points.rs
  milli/src/update/index_documents/extract/mod.rs
  milli/src/update/index_documents/mod.rs
  milli/src/update/index_documents/typed_chunk.rs
  milli/tests/assets/test_set.ndjson
  milli/tests/search/filters.rs
  milli/tests/search/mod.rs
  milli/tests/search/query_criteria.rs
  milli/tests/search/sort.rs
Labels: breaking-change

#360 Update version for the next release (v0.14.0)
  helpers/Cargo.toml
  http-ui/Cargo.toml
  infos/Cargo.toml
  milli/Cargo.toml
  search/Cargo.toml
Labels: skip-changelog

#361 Update version for the next release (v0.15.0)
  helpers/Cargo.toml
  http-ui/Cargo.toml
  infos/Cargo.toml
  milli/Cargo.toml
  search/Cargo.toml
Labels: skip-changelog

#367 Update version for the next release (v0.16.0)
  helpers/Cargo.toml
  http-ui/Cargo.toml
  infos/Cargo.toml
  milli/Cargo.toml
  search/Cargo.toml
Labels: skip-changelog

#373 Improve error message for bad sort syntax with geosearch
  milli/src/asc_desc.rs
Labels: breaking-change

#377 Update version for the next release (v0.17.0)
  helpers/Cargo.toml
  http-ui/Cargo.toml
  infos/Cargo.toml
  milli/Cargo.toml
  search/Cargo.toml
Labels: skip-changelog
