Repository meilisearch/milli, pull requests merged in 2021-06, with the labels that each got.

#204 Decorrelate Distinct, Asc/Desc, Filterable fields from the faceted fields
  http-ui/src/main.rs
  milli/src/criterion.rs
  milli/src/index.rs
  milli/src/lib.rs
  milli/src/search/criteria/asc_desc.rs
  milli/src/search/criteria/mod.rs
  milli/src/search/distinct/facet_distinct.rs
  milli/src/search/distinct/map_distinct.rs
  milli/src/search/distinct/mod.rs
  milli/src/search/distinct/noop_distinct.rs
  milli/src/search/facet/facet_distribution.rs
  milli/src/search/facet/filter_condition.rs
  milli/src/search/facet/mod.rs
  milli/src/search/mod.rs
  milli/src/update/settings.rs
Labels: breaking-change

#210 Check the benchmarks in the CI
  .github/workflows/test.yml
  benchmarks/benches/songs.rs
  benchmarks/benches/utils.rs
  benchmarks/benches/wiki.rs
Labels: benchmarks

#211 Update Cargo.toml for next release v0.3.0
  helpers/Cargo.toml
  http-ui/Cargo.toml
  infos/Cargo.toml
  milli/Cargo.toml
  search/Cargo.toml
Labels: skip-changelog

#213 Fix the benchmarks script and names
  Cargo.lock
  benchmarks/Cargo.toml
  benchmarks/benches/utils.rs
  benchmarks/scripts/compare.sh
Labels: benchmarks

#217 Improve the benchmarks readme
  benchmarks/README.md
Labels: skip-changelog

#215 Make the benchmark command more convenient in CI
  .github/workflows/benchmarks.yml
Labels: skip-changelog

#221 Use the index primary key when deleting documents
  milli/src/update/delete_documents.rs
Labels: bug

#219 Save the criteria field name in the fields ids map
  milli/src/criterion.rs
  milli/src/update/settings.rs
Labels: bug

#220 Make hard separators split phrase query
  milli/src/search/query_tree.rs
Labels: bug

#226 Update version for the next release (v0.3.1)
  Cargo.lock
  helpers/Cargo.toml
  http-ui/Cargo.toml
  infos/Cargo.toml
  milli/Cargo.toml
  search/Cargo.toml
Labels: skip-changelog

#225 Introduce the error handler
  Cargo.lock
  benchmarks/benches/utils.rs
  http-ui/src/main.rs
  infos/src/main.rs
  milli/Cargo.toml
  milli/src/criterion.rs
  milli/src/error.rs
  milli/src/heed_codec/facet/facet_value_string_codec.rs
  milli/src/heed_codec/facet/field_doc_id_facet_string_codec.rs
  milli/src/heed_codec/roaring_bitmap/bo_roaring_bitmap_codec.rs
  milli/src/heed_codec/roaring_bitmap/cbo_roaring_bitmap_codec.rs
  milli/src/index.rs
  milli/src/lib.rs
  milli/src/search/criteria/asc_desc.rs
  milli/src/search/criteria/attribute.rs
  milli/src/search/criteria/exactness.rs
  milli/src/search/criteria/final.rs
  milli/src/search/criteria/initial.rs
  milli/src/search/criteria/mod.rs
  milli/src/search/criteria/proximity.rs
  milli/src/search/criteria/typo.rs
  milli/src/search/criteria/words.rs
  milli/src/search/distinct/facet_distinct.rs
  milli/src/search/distinct/mod.rs
  milli/src/search/distinct/noop_distinct.rs
  milli/src/search/facet/facet_distribution.rs
  milli/src/search/facet/filter_condition.rs
  milli/src/search/facet/mod.rs
  milli/src/search/mod.rs
  milli/src/search/query_tree.rs
  milli/src/update/clear_documents.rs
  milli/src/update/delete_documents.rs
  milli/src/update/facets.rs
  milli/src/update/index_documents/merge_function.rs
  milli/src/update/index_documents/mod.rs
  milli/src/update/index_documents/store.rs
  milli/src/update/index_documents/transform.rs
  milli/src/update/settings.rs
  milli/src/update/update_builder.rs
  milli/src/update/word_prefix_docids.rs
  milli/src/update/word_prefix_pair_proximity_docids.rs
  milli/src/update/words_level_positions.rs
  milli/src/update/words_prefixes_fst.rs
  milli/tests/search/query_criteria.rs
Labels: breaking-change

#235 Update version for the next release (v0.4.0)
  Cargo.lock
  helpers/Cargo.toml
  http-ui/Cargo.toml
  infos/Cargo.toml
  milli/Cargo.toml
  search/Cargo.toml
Labels: skip-changelog

#242 Update version for the next release (v0.4.2)
  Cargo.lock
  helpers/Cargo.toml
  http-ui/Cargo.toml
  infos/Cargo.toml
  milli/Cargo.toml
  search/Cargo.toml
Labels: skip-changelog

#243 Rename FieldsDistribution into FieldDistribution
  milli/src/index.rs
  milli/src/lib.rs
  milli/src/update/clear_documents.rs
  milli/src/update/index_documents/transform.rs
Labels: breaking-change

#244 Update version for the next release (v0.5.0)
  Cargo.lock
  helpers/Cargo.toml
  http-ui/Cargo.toml
  infos/Cargo.toml
  milli/Cargo.toml
  search/Cargo.toml
Labels: skip-changelog

#256 Update version for the next release (v0.5.1)
  Cargo.lock
  helpers/Cargo.toml
  http-ui/Cargo.toml
  infos/Cargo.toml
  milli/Cargo.toml
  search/Cargo.toml
Labels: skip-changelog
