Repository meilisearch/milli, pull requests merged in 2022-10, with the labels that each got.

#653 Fix #652 - Change Spelling of `author` in `README.md`
  README.md
Labels: documentation

#654 Re-upload milli's logo
  .gitignore
  README.md
  assets/logo-black.svg
Labels: documentation, no breaking

#658 Add proximity calculation for the same word
  milli/src/update/index_documents/extract/extract_word_pair_proximity_docids.rs
Labels: DB breaking

#604 Speed up debug builds
  Cargo.toml
  benchmarks/Cargo.toml
  cli/Cargo.toml
  milli/src/documents/mod.rs
Labels: no breaking, maintenance

#655 Upgrade all dependencies
  benchmarks/Cargo.toml
  cli/Cargo.toml
  cli/src/main.rs
  filter-parser/Cargo.toml
  flatten-serde-json/Cargo.toml
  json-depth-checker/Cargo.toml
  milli/Cargo.toml
Labels: no breaking, dependencies

#586 Add settings to force milli to exhaustively compute the total number of hits
  milli/src/search/criteria/initial.rs
  milli/src/search/criteria/mod.rs
  milli/src/search/criteria/typo.rs
  milli/src/search/distinct/facet_distinct.rs
  milli/src/search/mod.rs
  milli/tests/search/query_criteria.rs
Labels: API breaking

#660 Store detected language per document during indexing
  milli/Cargo.toml
  milli/src/heed_codec/mod.rs
  milli/src/heed_codec/script_language_codec.rs
  milli/src/index.rs
  milli/src/update/clear_documents.rs
  milli/src/update/delete_documents.rs
  milli/src/update/index_documents/extract/extract_docid_word_positions.rs
  milli/src/update/index_documents/extract/mod.rs
  milli/src/update/index_documents/mod.rs
  milli/src/update/index_documents/typed_chunk.rs
Labels: no breaking, hacktoberfest-accepted

#669 Add method to create a new Index with specific creation dates
  milli/src/index.rs
Labels: no breaking

#616 Introduce an indexation abortion function when indexing documents
  benchmarks/benches/indexing.rs
  benchmarks/benches/utils.rs
  cli/src/main.rs
  milli/src/error.rs
  milli/src/index.rs
  milli/src/search/distinct/mod.rs
  milli/src/update/index_documents/mod.rs
  milli/src/update/index_documents/transform.rs
  milli/src/update/settings.rs
  milli/tests/search/distinct.rs
  milli/tests/search/facet_distribution.rs
  milli/tests/search/mod.rs
  milli/tests/search/query_criteria.rs
  milli/tests/search/typo_tolerance.rs
Labels: API breaking

#668 Fix many Clippy errors part 2
  milli/src/asc_desc.rs
  milli/src/documents/builder.rs
  milli/src/documents/mod.rs
  milli/src/fields_ids_map.rs
  milli/src/heed_codec/facet/facet_string_level_zero_value_codec.rs
  milli/src/heed_codec/facet/facet_string_zero_bounds_value_codec.rs
  milli/src/index.rs
  milli/src/lib.rs
  milli/src/search/criteria/asc_desc.rs
  milli/src/search/criteria/attribute.rs
  milli/src/search/criteria/geo.rs
  milli/src/search/criteria/initial.rs
  milli/src/search/criteria/mod.rs
  milli/src/search/criteria/proximity.rs
  milli/src/search/criteria/typo.rs
  milli/src/search/criteria/words.rs
  milli/src/search/facet/facet_distribution.rs
  milli/src/search/facet/filter.rs
  milli/src/search/matches/matching_words.rs
  milli/src/search/matches/mod.rs
  milli/src/search/query_tree.rs
  milli/src/update/delete_documents.rs
  milli/src/update/facets.rs
  milli/src/update/index_documents/enrich.rs
  milli/src/update/index_documents/extract/extract_docid_word_positions.rs
  milli/src/update/index_documents/extract/extract_fid_docid_facet_values.rs
  milli/src/update/index_documents/extract/mod.rs
  milli/src/update/prefix_word_pairs/prefix_word.rs
  milli/src/update/prefix_word_pairs/word_prefix.rs
Labels: no breaking

#664 Fix phrase search containing stop words
  milli/src/search/criteria/attribute.rs
  milli/src/search/criteria/exactness.rs
  milli/src/search/criteria/mod.rs
  milli/src/search/criteria/proximity.rs
  milli/src/search/criteria/typo.rs
  milli/src/search/query_tree.rs
  milli/tests/search/mod.rs
  milli/tests/search/phrase_search.rs
Labels: no breaking

#676 chore: added `IN`,`NOT IN` to `invalid_filter` msg
  filter-parser/src/error.rs
  filter-parser/src/lib.rs
Labels: no breaking, hacktoberfest-accepted

#677 run the tests in all workspaces
  .github/workflows/rust.yml
Labels: no breaking
