Repository meilisearch/milli, pull requests merged in 2022-07, with the labels that each got.

#575 Bump charabia
  milli/Cargo.toml
Labels: skip changelog, no breaking

#577 Fix deserialisation of NDJson documents in benchmarks
  benchmarks/benches/utils.rs
Labels: bug, benchmarks, skip changelog, no breaking, performance

#572 Add reindexing benchmarks
  benchmarks/benches/indexing.rs
Labels: benchmarks, skip changelog, no breaking, performance

#578 Bump uuid to 1.1.2
  milli/Cargo.toml
  milli/src/update/index_documents/transform.rs
Labels: no breaking

#588 Fix name of "release_date" facet in movies benchmarks
  benchmarks/benches/indexing.rs
Labels: benchmarks, no breaking

#584 Chores: Enhance smart-crop code comments
  milli/src/search/matches/mod.rs
Labels: skip changelog, no breaking, maintenance

#561 Enriched documents batch reader
  benchmarks/benches/indexing.rs
  benchmarks/benches/utils.rs
  cli/src/main.rs
  http-ui/src/main.rs
  milli/Cargo.toml
  milli/fuzz/.gitignore
  milli/fuzz/fuzz_targets/indexing.rs
  milli/src/documents/builder.rs
  milli/src/documents/enriched.rs
  milli/src/documents/mod.rs
  milli/src/documents/reader.rs
  milli/src/documents/serde_impl.rs
  milli/src/error.rs
  milli/src/index.rs
  milli/src/lib.rs
  milli/src/search/distinct/mod.rs
  milli/src/search/facet/filter.rs
  milli/src/update/clear_documents.rs
  milli/src/update/delete_documents.rs
  milli/src/update/index_documents/enrich.rs
  milli/src/update/index_documents/extract/extract_geo_points.rs
  milli/src/update/index_documents/mod.rs
  milli/src/update/index_documents/transform.rs
  milli/src/update/mod.rs
  milli/src/update/settings.rs
  milli/tests/search/facet_distribution.rs
  milli/tests/search/mod.rs
  milli/tests/search/query_criteria.rs
  milli/tests/search/typo_tolerance.rs
Labels: no breaking, performance

#592 Fix(smart-crop): Ensure that matches are all highlighted
  benchmarks/Cargo.toml
  cli/Cargo.toml
  filter-parser/Cargo.toml
  flatten-serde-json/Cargo.toml
  helpers/Cargo.toml
  http-ui/Cargo.toml
  infos/Cargo.toml
  json-depth-checker/Cargo.toml
  milli/Cargo.toml
  milli/src/search/matches/mod.rs
Labels: no breaking

#595 Update version for next release (v0.32.0)
  benchmarks/Cargo.toml
  cli/Cargo.toml
  filter-parser/Cargo.toml
  flatten-serde-json/Cargo.toml
  helpers/Cargo.toml
  http-ui/Cargo.toml
  infos/Cargo.toml
  json-depth-checker/Cargo.toml
  milli/Cargo.toml
Labels: skip changelog
