Repository meilisearch/milli, pull requests merged in 2022-04, with the labels that each got.

#478 Disable typo on attribute
  cli/src/main.rs
  infos/src/main.rs
  milli/src/index.rs
  milli/src/search/criteria/mod.rs
  milli/src/search/query_tree.rs
  milli/src/update/clear_documents.rs
  milli/src/update/delete_documents.rs
  milli/src/update/index_documents/extract/extract_word_docids.rs
  milli/src/update/index_documents/extract/mod.rs
  milli/src/update/index_documents/helpers/grenad_helpers.rs
  milli/src/update/index_documents/helpers/mod.rs
  milli/src/update/index_documents/mod.rs
  milli/src/update/index_documents/typed_chunk.rs
  milli/src/update/settings.rs
  milli/src/update/word_prefix_docids.rs
  milli/tests/search/query_criteria.rs
  milli/tests/search/typo_tolerance.rs
Labels: breaking-change

#486 Update version (v0.25.0)
  cli/Cargo.toml
  helpers/Cargo.toml
  http-ui/Cargo.toml
  infos/Cargo.toml
  milli/Cargo.toml
Labels: skip-changelog

#458 Nested fields
  Cargo.toml
  benchmarks/benches/indexing.rs
  benchmarks/benches/utils.rs
  cli/src/main.rs
  flatten-serde-json/Cargo.toml
  flatten-serde-json/README.md
  flatten-serde-json/fuzz/Cargo.toml
  flatten-serde-json/fuzz/fuzz_targets/flatten.rs
  flatten-serde-json/src/lib.rs
  flatten-serde-json/src/main.rs
  http-ui/src/main.rs
  milli/Cargo.toml
  milli/src/documents/mod.rs
  milli/src/error.rs
  milli/src/index.rs
  milli/src/lib.rs
  milli/src/search/distinct/mod.rs
  milli/src/search/facet/facet_distribution.rs
  milli/src/search/facet/filter.rs
  milli/src/search/mod.rs
  milli/src/update/clear_documents.rs
  milli/src/update/delete_documents.rs
  milli/src/update/index_documents/extract/extract_geo_points.rs
  milli/src/update/index_documents/extract/mod.rs
  milli/src/update/index_documents/mod.rs
  milli/src/update/index_documents/transform.rs
  milli/src/update/settings.rs
  milli/tests/search/mod.rs
  milli/tests/search/query_criteria.rs
  milli/tests/search/typo_tolerance.rs
Labels: breaking-change

#490 Enforce labelling for the PRs
  .github/release-draft-template.yml
  .github/workflows/enforce-label.yml
Labels: no breaking

#492 Add the new `Specify breaking` check to bors.toml
  bors.toml
Labels: no breaking

#489 fix distinct count bug
  cli/src/main.rs
  milli/src/search/mod.rs
  milli/tests/search/distinct.rs
Labels: no breaking

#496 Improve the performances of the flattening subcrate
  flatten-serde-json/Cargo.toml
  flatten-serde-json/benches/benchmarks.rs
  flatten-serde-json/src/lib.rs
Labels: no breaking

#493 Use smartstring to store the external id in our hashmap
  milli/Cargo.toml
  milli/src/update/index_documents/mod.rs
  milli/src/update/index_documents/transform.rs
Labels: no breaking

#494 Only flatten the required objects
  Cargo.toml
  json-depth-checker/Cargo.toml
  json-depth-checker/benches/depth.rs
  json-depth-checker/fuzz/Cargo.toml
  json-depth-checker/fuzz/fuzz_targets/depth.rs
  json-depth-checker/src/lib.rs
  milli/Cargo.toml
  milli/src/update/index_documents/transform.rs
Labels: no breaking

#497 Update version for the next release (v0.26.1)
  cli/Cargo.toml
  helpers/Cargo.toml
  http-ui/Cargo.toml
  infos/Cargo.toml
  milli/Cargo.toml
Labels: skip changelog

#483 Enhance matching words
  benchmarks/Cargo.toml
  benchmarks/benches/formatting.rs
  http-ui/src/main.rs
  milli/src/lib.rs
  milli/src/search/matches/matching_words.rs
  milli/src/search/matches/mod.rs
  milli/src/search/matching_words.rs
  milli/src/search/mod.rs
  milli/src/search/query_tree.rs
Labels: API breaking

#499 fix min-word-len-for-typo not reset properly
  milli/src/update/settings.rs
Labels: no breaking

#498 Get rid of the threshold when comparing benchmarks
  benchmarks/scripts/compare.sh
Labels: skip changelog

#504 Add a test to make sure that long words are handled
  milli/src/update/index_documents/mod.rs
Labels: no breaking

#505 normalize exact words
  milli/src/update/settings.rs
Labels: no breaking

#508 First version of new CONTRIBUTING.md
  CONTRIBUTING.md
  README.md
Labels: no breaking

#503 Improve the fuzzer of the flatten crate
  flatten-serde-json/fuzz/Cargo.toml
  flatten-serde-json/fuzz/fuzz_targets/flatten.rs
Labels: skip changelog

#509 Remove pr_status from bors settings
  bors.toml
Labels: no breaking

#515 Improve the README
  README.md
  cli/Cargo.toml
  filter-parser/Cargo.toml
  helpers/Cargo.toml
  json-depth-checker/Cargo.toml
  json-depth-checker/src/lib.rs
Labels: no breaking

#516 Fix the indexing fuzzer
  milli/fuzz/fuzz_targets/indexing.rs
Labels: skip changelog, no breaking

#514 Stop flattening every field
  milli/src/update/index_documents/mod.rs
  milli/src/update/index_documents/transform.rs
Labels: no breaking

#510 v0.26.3 release: normalizes exact word
  benchmarks/Cargo.toml
  cli/Cargo.toml
  filter-parser/Cargo.toml
  flatten-serde-json/Cargo.toml
  helpers/Cargo.toml
  http-ui/Cargo.toml
  infos/Cargo.toml
  json-depth-checker/Cargo.toml
  milli/Cargo.toml
  milli/src/update/index_documents/mod.rs
  milli/src/update/index_documents/transform.rs
  milli/src/update/settings.rs
Labels: no breaking

#506 fix cargo warnings
  milli/src/search/query_tree.rs
Labels: no breaking

#511 Update version in every workspace
  benchmarks/Cargo.toml
  cli/Cargo.toml
  filter-parser/Cargo.toml
  flatten-serde-json/Cargo.toml
  helpers/Cargo.toml
  http-ui/Cargo.toml
  infos/Cargo.toml
  json-depth-checker/Cargo.toml
  milli/Cargo.toml
Labels: skip changelog

#517 Make nightly CI run every week
  .github/workflows/rust.yml
  bors.toml
Labels: no breaking

#518 Return facets even when there is no value associated to it
  milli/src/search/facet/facet_distribution.rs
  milli/tests/search/facet_distribution.rs
  milli/tests/search/mod.rs
Labels: no breaking
