Repository meilisearch/milli, pull requests merged in 2022-09, with the labels that each got.

#620 Fix word criterion
  benchmarks/Cargo.toml
  cli/Cargo.toml
  filter-parser/Cargo.toml
  flatten-serde-json/Cargo.toml
  helpers/Cargo.toml
  http-ui/Cargo.toml
  infos/Cargo.toml
  json-depth-checker/Cargo.toml
  milli/Cargo.toml
  milli/src/search/query_tree.rs
Labels: no breaking

#621 Add CI to update the Milli version
  .github/workflows/update-cargo-toml-version.yml
Labels: no breaking, maintenance

#622 Minor fixes in the just added update-version CI
  .github/workflows/update-cargo-toml-version.yml
Labels: skip changelog

#628 Make sure that long words are ignored
  milli/src/update/index_documents/extract/extract_docid_word_positions.rs
  milli/src/update/index_documents/helpers/mod.rs
  milli/src/update/index_documents/mod.rs
Labels: bug, no breaking

#631 Revert "Remove Bors required test for Windows"
  bors.toml
Labels: no breaking, maintenance

#633 Upgrade ubuntu-18.04 to 20.04
  .github/workflows/rust.yml
  bors.toml
Labels: no breaking, maintenance

#632 Make charabia default feature optional
  milli/Cargo.toml
Labels: enhancement, no breaking, maintenance

#637 We avoid skipping errors in the indexing pipeline
  milli/src/update/index_documents/mod.rs
Labels: bug, no breaking

#635 Use an unstable algorithm for `grenad::Sorter` when possible
  milli/Cargo.toml
  milli/src/update/index_documents/extract/extract_docid_word_positions.rs
  milli/src/update/index_documents/extract/extract_facet_number_docids.rs
  milli/src/update/index_documents/extract/extract_facet_string_docids.rs
  milli/src/update/index_documents/extract/extract_fid_docid_facet_values.rs
  milli/src/update/index_documents/extract/extract_fid_word_count_docids.rs
  milli/src/update/index_documents/extract/extract_word_docids.rs
  milli/src/update/index_documents/extract/extract_word_pair_proximity_docids.rs
  milli/src/update/index_documents/extract/extract_word_position_docids.rs
  milli/src/update/index_documents/helpers/grenad_helpers.rs
  milli/src/update/index_documents/mod.rs
  milli/src/update/index_documents/transform.rs
  milli/src/update/word_prefix_docids.rs
  milli/src/update/words_prefix_position_docids.rs
Labels: indexing, no breaking, performance

#636 Remove unused `infos`, `http-ui`, and `milli/fuzz`, crates
  CONTRIBUTING.md
  Cargo.toml
  README.md
  http-ui/Cargo.toml
  http-ui/public/bulma-prefers-dark.min.css
  http-ui/public/bulma.min.css
  http-ui/public/filesize.min.js
  http-ui/public/jquery-3.4.1.min.js
  http-ui/public/logo-black.svg
  http-ui/public/logo-white.svg
  http-ui/public/script.js
  http-ui/public/style.css
  http-ui/public/updates-script.js
  http-ui/src/main.rs
  http-ui/src/update_store.rs
  http-ui/templates/index.html
  http-ui/templates/updates.html
  infos/Cargo.toml
  infos/src/main.rs
  milli/README.md
  milli/fuzz/.gitignore
  milli/fuzz/Cargo.toml
  milli/fuzz/fuzz_targets/indexing.rs
Labels: no breaking, maintenance

#641 Remove `helpers` crate
  Cargo.toml
  README.md
  helpers/Cargo.toml
  helpers/src/main.rs
Labels: no breaking, maintenance

#642 Remove LTO in release profile
  Cargo.toml
Labels: no breaking, maintenance, performance
