Repository meilisearch/milli, pull requests merged in 2022-08, with the labels that each got.

#599 fix: Remove whitespace trimming during document id validation
  milli/src/update/index_documents/enrich.rs
  milli/src/update/index_documents/mod.rs
Labels: bug, no breaking

#601 Introduce snapshot tests
  .gitignore
  milli/Cargo.toml
  milli/src/error.rs
  milli/src/index.rs
  milli/src/lib.rs
  milli/src/search/criteria/attribute.rs
  milli/src/search/criteria/typo.rs
  milli/src/search/facet/filter.rs
  milli/src/search/matches/mod.rs
  milli/src/search/query_tree.rs
  milli/src/snapshot_tests.rs
  milli/src/snapshots/index.rs/initial_field_distribution/1/field_distribution.snap
  milli/src/snapshots/index.rs/initial_field_distribution/field_distribution.snap
  milli/src/update/facets.rs
  milli/src/update/snapshots/facets.rs/test_facets_number/default/facet_id_f64_docids.hash.snap
  milli/src/update/snapshots/facets.rs/test_facets_number/large_groups_large_levels/facet_id_f64_docids.hash.snap
  milli/src/update/snapshots/facets.rs/test_facets_number/large_groups_small_levels/facet_id_f64_docids.hash.snap
  milli/src/update/snapshots/facets.rs/test_facets_number/small_groups_large_levels/facet_id_f64_docids.hash.snap
  milli/src/update/snapshots/facets.rs/test_facets_number/small_groups_small_levels/facet_id_f64_docids.hash.snap
  milli/src/update/snapshots/facets.rs/test_facets_number/tiny_groups_tiny_levels/facet_id_f64_docids.hash.snap
  milli/src/update/snapshots/facets.rs/test_facets_string/default/facet_id_string_docids.hash.snap
  milli/src/update/snapshots/facets.rs/test_facets_string/tiny_groups_tiny_levels/facet_id_string_docids.hash.snap
  milli/src/update/snapshots/word_prefix_pair_proximity_docids.rs/test_update/initial/word_prefix_pair_proximity_docids.snap
  milli/src/update/snapshots/word_prefix_pair_proximity_docids.rs/test_update/update/word_prefix_pair_proximity_docids.snap
  milli/src/update/word_prefix_pair_proximity_docids.rs
Labels: no breaking

#606 Make binaries faster on release profile through better compile options
  Cargo.toml
Labels: no breaking, maintenance, performance

#602 Use mimalloc as the default allocator
  benchmarks/Cargo.toml
  benchmarks/benches/formatting.rs
  benchmarks/benches/indexing.rs
  benchmarks/benches/search_geo.rs
  benchmarks/benches/search_songs.rs
  benchmarks/benches/search_wiki.rs
  cli/Cargo.toml
  cli/src/main.rs
  helpers/Cargo.toml
  helpers/src/main.rs
  http-ui/Cargo.toml
  http-ui/src/main.rs
  infos/Cargo.toml
  infos/src/main.rs
  milli/fuzz/Cargo.toml
  milli/fuzz/fuzz_targets/indexing.rs
Labels: benchmarks, no breaking

#594 Fix(Search): Fix phrase search candidates computation
  milli/src/search/criteria/mod.rs
  milli/src/search/criteria/proximity.rs
Labels: bug, no breaking

#608 Fix soft deleted documents
  milli/src/update/index_documents/mod.rs
  milli/src/update/index_documents/transform.rs
Labels: bug, indexing, no breaking

#587 Word prefix pair proximity docids indexation refactor
  infos/src/main.rs
  milli/src/heed_codec/mod.rs
  milli/src/heed_codec/str_str_u8_codec.rs
  milli/src/lib.rs
  milli/src/update/index_documents/extract/extract_word_pair_proximity_docids.rs
  milli/src/update/snapshots/word_prefix_pair_proximity_docids.rs/test_update/update/word_prefix_pair_proximity_docids.hash.snap
  milli/src/update/snapshots/word_prefix_pair_proximity_docids.rs/test_update/update/word_prefix_pair_proximity_docids.snap
  milli/src/update/word_prefix_pair_proximity_docids.rs
Labels: no breaking, performance

#607 Better threshold
  benchmarks/benches/indexing.rs
  benchmarks/benches/utils.rs
  cli/Cargo.toml
  cli/src/main.rs
  helpers/Cargo.toml
  helpers/src/main.rs
  http-ui/Cargo.toml
  http-ui/src/main.rs
  http-ui/src/update_store.rs
  infos/Cargo.toml
  infos/src/main.rs
  milli/Cargo.toml
  milli/src/error.rs
  milli/src/index.rs
  milli/src/update/delete_documents.rs
  milli/src/update/index_documents/mod.rs
Labels: API breaking

#596 Filter operators: NOT + IN[..]
  filter-parser/Cargo.toml
  filter-parser/src/condition.rs
  filter-parser/src/error.rs
  filter-parser/src/lib.rs
  filter-parser/src/value.rs
  http-ui/src/main.rs
  milli/src/search/facet/filter.rs
  milli/tests/assets/test_set.ndjson
  milli/tests/search/filters.rs
  milli/tests/search/mod.rs
Labels: API breaking

#609 Retry downloading the benchmarks datasets
  benchmarks/build.rs
Labels: skip changelog, no breaking

#610 Share heed between all sub-crates
  benchmarks/Cargo.toml
  milli/fuzz/Cargo.toml
  milli/fuzz/fuzz_targets/indexing.rs
Labels: skip changelog, no breaking, maintenance

#598 Matching query terms policy
  benchmarks/benches/utils.rs
  milli/src/lib.rs
  milli/src/search/mod.rs
  milli/src/search/query_tree.rs
  milli/src/update/index_documents/mod.rs
  milli/tests/search/distinct.rs
  milli/tests/search/filters.rs
  milli/tests/search/mod.rs
  milli/tests/search/query_criteria.rs
  milli/tests/search/sort.rs
  milli/tests/search/typo_tolerance.rs
Labels: API breaking

#612 Remove Bors required test for Windows
  bors.toml
Labels: no breaking, maintenance

#613 Update version for next release (v0.33.0)
  benchmarks/Cargo.toml
  cli/Cargo.toml
  filter-parser/Cargo.toml
  flatten-serde-json/Cargo.toml
  helpers/Cargo.toml
  http-ui/Cargo.toml
  infos/Cargo.toml
  json-depth-checker/Cargo.toml
  milli/Cargo.toml
Labels: skip changelog

#611 Upgrade charabia v0.6.0
  http-ui/Cargo.toml
  http-ui/src/main.rs
  milli/Cargo.toml
Labels: API breaking

#615 Remove the artifacts of the past
  milli/src/search/facet/grammar.pest
Labels: no breaking

#617 Accept integers as document ids again
  milli/src/documents/builder.rs
Labels: no breaking

#618 Update version for next release (v0.33.1) in Cargo.toml
  benchmarks/Cargo.toml
  cli/Cargo.toml
  filter-parser/Cargo.toml
  flatten-serde-json/Cargo.toml
  helpers/Cargo.toml
  http-ui/Cargo.toml
  infos/Cargo.toml
  json-depth-checker/Cargo.toml
  milli/Cargo.toml
Labels: skip changelog
