Repository meilisearch/milli, pull requests merged in 2022-12, with the labels that each got.

#715 Fix benchmark CI
  .github/workflows/manual_benchmarks.yml
  .github/workflows/push_benchmarks_indexing.yml
  .github/workflows/push_benchmarks_search_geo.yml
  .github/workflows/push_benchmarks_search_songs.yml
  .github/workflows/push_benchmarks_search_wiki.yml
Labels: no breaking, maintenance

#706 Limit the reindexing caused by updating settings when not needed
  milli/src/index.rs
  milli/src/update/settings.rs
Labels: no breaking

#722 Geosearch for zero radius
  milli/src/search/facet/filter.rs
Labels: bug, no breaking

#729 Fix distincted exhaustive hits
  milli/src/search/criteria/asc_desc.rs
  milli/src/search/criteria/attribute.rs
  milli/src/search/criteria/exactness.rs
  milli/src/search/criteria/final.rs
  milli/src/search/criteria/geo.rs
  milli/src/search/criteria/initial.rs
  milli/src/search/criteria/mod.rs
  milli/src/search/criteria/proximity.rs
  milli/src/search/criteria/typo.rs
  milli/src/search/criteria/words.rs
  milli/src/search/mod.rs
  milli/tests/search/distinct.rs
Labels: bug, no breaking

#734 Fix bug 2945/3021 (missing key in documents database)
  milli/src/index.rs
  milli/src/update/delete_documents.rs
  milli/src/update/index_documents/mod.rs
Labels: bug, no breaking

#737 Fix typo initial candidates computation
  milli/src/search/criteria/typo.rs
  milli/src/search/criteria/words.rs
Labels: bug, no breaking

#740 Fix two nightly errors
  filter-parser/src/error.rs
  filter-parser/src/lib.rs
Labels: skip changelog, no breaking, maintenance

#741 Add test reproducing the bug fixed by #737
  milli/tests/search/distinct.rs
Labels: skip changelog, no breaking

#728 Add some integration tests on the sort criterion
  milli/src/search/criteria/asc_desc.rs
Labels: no breaking, maintenance

#739 Cherry pick bug fixes for v0.37.3
  milli/src/index.rs
  milli/src/search/criteria/typo.rs
  milli/src/search/criteria/words.rs
  milli/src/update/delete_documents.rs
  milli/src/update/index_documents/mod.rs
Labels: skip changelog, no breaking

#743 Fix finite pagination with placeholder search
  milli/src/search/criteria/initial.rs
Labels: no breaking

#745 Cherry pick placeholder search fix
  milli/src/search/criteria/initial.rs
Labels: skip changelog

#747 Soft-deletion computation no longer depends on the mapsize
  milli/src/index.rs
  milli/src/update/delete_documents.rs
  milli/src/update/facet/delete.rs
  milli/src/update/facet/mod.rs
  milli/src/update/index_documents/mod.rs
  milli/src/update/mod.rs
  milli/src/update/prefix_word_pairs/mod.rs
  milli/src/update/snapshots/delete_documents.rs/delete_documents_with_numbers_as_primary_key/always_hard/documents_ids.snap
  milli/src/update/snapshots/delete_documents.rs/delete_documents_with_numbers_as_primary_key/always_hard/facet_id_exists_docids.snap
  milli/src/update/snapshots/delete_documents.rs/delete_documents_with_numbers_as_primary_key/always_hard/soft_deleted_documents_ids.snap
  milli/src/update/snapshots/delete_documents.rs/delete_documents_with_numbers_as_primary_key/always_hard/word_docids.snap
  milli/src/update/snapshots/delete_documents.rs/delete_documents_with_numbers_as_primary_key/always_hard/word_pair_proximity_docids.snap
  milli/src/update/snapshots/delete_documents.rs/delete_documents_with_numbers_as_primary_key/always_soft/documents_ids.snap
  milli/src/update/snapshots/delete_documents.rs/delete_documents_with_numbers_as_primary_key/always_soft/facet_id_exists_docids.snap
  milli/src/update/snapshots/delete_documents.rs/delete_documents_with_numbers_as_primary_key/always_soft/soft_deleted_documents_ids.snap
  milli/src/update/snapshots/delete_documents.rs/delete_documents_with_numbers_as_primary_key/always_soft/word_docids.snap
  milli/src/update/snapshots/delete_documents.rs/delete_documents_with_numbers_as_primary_key/always_soft/word_pair_proximity_docids.snap
  milli/src/update/snapshots/delete_documents.rs/delete_documents_with_strange_primary_key/always_hard/documents_ids.snap
  milli/src/update/snapshots/delete_documents.rs/delete_documents_with_strange_primary_key/always_hard/soft_deleted_documents_ids.snap
  milli/src/update/snapshots/delete_documents.rs/delete_documents_with_strange_primary_key/always_hard/word_docids.snap
  milli/src/update/snapshots/delete_documents.rs/delete_documents_with_strange_primary_key/always_hard/word_pair_proximity_docids.snap
  milli/src/update/snapshots/delete_documents.rs/delete_documents_with_strange_primary_key/always_soft/documents_ids.snap
  milli/src/update/snapshots/delete_documents.rs/delete_documents_with_strange_primary_key/always_soft/soft_deleted_documents_ids.snap
  milli/src/update/snapshots/delete_documents.rs/delete_documents_with_strange_primary_key/always_soft/word_docids.snap
  milli/src/update/snapshots/delete_documents.rs/delete_documents_with_strange_primary_key/always_soft/word_pair_proximity_docids.snap
  milli/src/update/snapshots/delete_documents.rs/filtered_placeholder_search_should_not_return_deleted_documents/always_hard/facet_id_exists_docids.snap
  milli/src/update/snapshots/delete_documents.rs/filtered_placeholder_search_should_not_return_deleted_documents/always_hard/facet_id_f64_docids.snap
  milli/src/update/snapshots/delete_documents.rs/filtered_placeholder_search_should_not_return_deleted_documents/always_hard/facet_id_string_docids.snap
  milli/src/update/snapshots/delete_documents.rs/filtered_placeholder_search_should_not_return_deleted_documents/always_hard/soft_deleted_documents_ids.snap
  milli/src/update/snapshots/delete_documents.rs/filtered_placeholder_search_should_not_return_deleted_documents/always_hard/word_docids.snap
  milli/src/update/snapshots/delete_documents.rs/filtered_placeholder_search_should_not_return_deleted_documents/always_hard/word_pair_proximity_docids.snap
  milli/src/update/snapshots/delete_documents.rs/filtered_placeholder_search_should_not_return_deleted_documents/always_soft/facet_id_exists_docids.snap
  milli/src/update/snapshots/delete_documents.rs/filtered_placeholder_search_should_not_return_deleted_documents/always_soft/facet_id_f64_docids.snap
  milli/src/update/snapshots/delete_documents.rs/filtered_placeholder_search_should_not_return_deleted_documents/always_soft/facet_id_string_docids.snap
  milli/src/update/snapshots/delete_documents.rs/filtered_placeholder_search_should_not_return_deleted_documents/always_soft/soft_deleted_documents_ids.snap
  milli/src/update/snapshots/delete_documents.rs/filtered_placeholder_search_should_not_return_deleted_documents/always_soft/word_docids.snap
  milli/src/update/snapshots/delete_documents.rs/filtered_placeholder_search_should_not_return_deleted_documents/always_soft/word_pair_proximity_docids.snap
  milli/src/update/snapshots/delete_documents.rs/geo_filtered_placeholder_search_should_not_return_deleted_documents/always_hard/facet_id_f64_docids.snap
  milli/src/update/snapshots/delete_documents.rs/geo_filtered_placeholder_search_should_not_return_deleted_documents/always_hard/facet_id_string_docids.snap
  milli/src/update/snapshots/delete_documents.rs/geo_filtered_placeholder_search_should_not_return_deleted_documents/always_hard/soft_deleted_documents_ids.snap
  milli/src/update/snapshots/delete_documents.rs/geo_filtered_placeholder_search_should_not_return_deleted_documents/always_soft/facet_id_f64_docids.snap
  milli/src/update/snapshots/delete_documents.rs/geo_filtered_placeholder_search_should_not_return_deleted_documents/always_soft/facet_id_string_docids.snap
  milli/src/update/snapshots/delete_documents.rs/geo_filtered_placeholder_search_should_not_return_deleted_documents/always_soft/soft_deleted_documents_ids.snap
  milli/src/update/snapshots/delete_documents.rs/get_documents_should_not_return_deleted_documents/always_hard/soft_deleted_documents_ids.snap
  milli/src/update/snapshots/delete_documents.rs/get_documents_should_not_return_deleted_documents/always_soft/soft_deleted_documents_ids.snap
  milli/src/update/snapshots/delete_documents.rs/search_should_not_return_deleted_documents/always_hard/soft_deleted_documents_ids.snap
  milli/src/update/snapshots/delete_documents.rs/search_should_not_return_deleted_documents/always_soft/soft_deleted_documents_ids.snap
  milli/src/update/snapshots/delete_documents.rs/stats_should_not_return_deleted_documents/always_hard/soft_deleted_documents_ids.snap
  milli/src/update/snapshots/delete_documents.rs/stats_should_not_return_deleted_documents/always_soft/soft_deleted_documents_ids.snap
Labels: indexing, no breaking, performance

#750 Fix hard-deletion of an external id that was soft-deleted and then reimported - main
  milli/src/external_documents_ids.rs
  milli/src/index.rs
  milli/src/update/delete_documents.rs
Labels: bug, no breaking

#754 Fix hard-deletion of an external id that was soft-deleted and then reimported - release-v0.37.5
  milli/src/external_documents_ids.rs
  milli/src/index.rs
  milli/src/update/delete_documents.rs
Labels: bug, no breaking

#742 Add a "Criterion implementation strategy" parameter to Search
  cli/src/main.rs
  milli/src/lib.rs
  milli/src/search/criteria/asc_desc.rs
  milli/src/search/criteria/attribute.rs
  milli/src/search/criteria/mod.rs
  milli/src/search/criteria/proximity.rs
  milli/src/search/mod.rs
Labels: benchmarks, no breaking, maintenance
