Repository meilisearch/milli, pull requests merged in 2022-06, with the labels that each got.

#535 Reintroduce the max values by facet limit
  milli/src/search/facet/facet_distribution.rs
Labels: no breaking

#540 Integrate charabia
  benchmarks/benches/formatting.rs
  http-ui/src/main.rs
  milli/Cargo.toml
  milli/src/lib.rs
  milli/src/search/matches/matching_words.rs
  milli/src/search/matches/mod.rs
  milli/src/search/mod.rs
  milli/src/search/query_tree.rs
  milli/src/update/index_documents/extract/extract_docid_word_positions.rs
  milli/src/update/settings.rs
Labels: DB breaking, API breaking

#545 bump version number
  benchmarks/Cargo.toml
  cli/Cargo.toml
  filter-parser/Cargo.toml
  flatten-serde-json/Cargo.toml
  helpers/Cargo.toml
  http-ui/Cargo.toml
  infos/Cargo.toml
  json-depth-checker/Cargo.toml
  milli/Cargo.toml
Labels: no breaking

#543 Fix wrong internal ids assignments
  milli/src/update/index_documents/mod.rs
  milli/src/update/index_documents/transform.rs
Labels: bug, no breaking

#547 Update version for next release (v0.29.1)
  benchmarks/Cargo.toml
  cli/Cargo.toml
  filter-parser/Cargo.toml
  flatten-serde-json/Cargo.toml
  helpers/Cargo.toml
  http-ui/Cargo.toml
  infos/Cargo.toml
  json-depth-checker/Cargo.toml
  milli/Cargo.toml
Labels: skip changelog

#548 Setup the new limits on the number of facet values to return
  milli/src/search/facet/facet_distribution.rs
Labels: documentation, no breaking

#549 Bump the version to 0.29.2
  benchmarks/Cargo.toml
  cli/Cargo.toml
  filter-parser/Cargo.toml
  flatten-serde-json/Cargo.toml
  helpers/Cargo.toml
  http-ui/Cargo.toml
  infos/Cargo.toml
  json-depth-checker/Cargo.toml
  milli/Cargo.toml
Labels: skip changelog

#550 Add the two new pagination and faceting settings
  milli/src/index.rs
  milli/src/lib.rs
  milli/src/search/facet/facet_distribution.rs
  milli/src/search/facet/mod.rs
  milli/src/search/mod.rs
  milli/src/update/settings.rs
Labels: no breaking

#552 Fix escaped quotes in filter
  benchmarks/Cargo.toml
  cli/Cargo.toml
  filter-parser/Cargo.toml
  filter-parser/src/lib.rs
  flatten-serde-json/Cargo.toml
  helpers/Cargo.toml
  http-ui/Cargo.toml
  infos/Cargo.toml
  json-depth-checker/Cargo.toml
  milli/Cargo.toml
  milli/src/search/facet/filter.rs
Labels: no breaking

#554 Ensure that Index methods are not bypassed by Meilisearch
  cli/src/main.rs
  infos/src/main.rs
  milli/src/index.rs
  milli/src/update/delete_documents.rs
Labels: API breaking, maintenance

#558 Deletion benchmarks
  benchmarks/Cargo.toml
  benchmarks/benches/indexing.rs
Labels: no breaking, maintenance

#560 Update version for next release (v0.30.0)
  benchmarks/Cargo.toml
  cli/Cargo.toml
  filter-parser/Cargo.toml
  flatten-serde-json/Cargo.toml
  helpers/Cargo.toml
  http-ui/Cargo.toml
  infos/Cargo.toml
  json-depth-checker/Cargo.toml
  milli/Cargo.toml
Labels: skip changelog

#565 Bump the milli version to 0.31.0
  benchmarks/Cargo.toml
  cli/Cargo.toml
  filter-parser/Cargo.toml
  flatten-serde-json/Cargo.toml
  helpers/Cargo.toml
  http-ui/Cargo.toml
  infos/Cargo.toml
  json-depth-checker/Cargo.toml
  milli/Cargo.toml
Labels: skip changelog

#563 Improve the `estimatedNbHits` when a `distinctAttribute` is specified
  milli/src/search/mod.rs
Labels: no breaking

#566 Introduce the copy_to_path method on the Index
  milli/src/index.rs
Labels: no breaking

#567 Bump the milli version to 0.31.1
  benchmarks/Cargo.toml
  cli/Cargo.toml
  filter-parser/Cargo.toml
  flatten-serde-json/Cargo.toml
  helpers/Cargo.toml
  http-ui/Cargo.toml
  infos/Cargo.toml
  json-depth-checker/Cargo.toml
  milli/Cargo.toml
Labels: skip changelog
