Repository meilisearch/milli, pull requests merged in 2022-05, with the labels that each got.

#522 Do not generate keys that are too long for LMDB
  milli/src/update/index_documents/mod.rs
  milli/src/update/word_prefix_docids.rs
  milli/src/update/word_prefix_pair_proximity_docids.rs
  milli/src/update/words_prefix_position_docids.rs
Labels: bug, no breaking

#520 fix mistake in Settings initialization
  milli/src/update/settings.rs
Labels: no breaking

#519 Release v0.26.4: returns facets even when there is no value associated to it + bug fix during indexation + bug fix on typo-tolerance
  benchmarks/Cargo.toml
  cli/Cargo.toml
  filter-parser/Cargo.toml
  flatten-serde-json/Cargo.toml
  helpers/Cargo.toml
  http-ui/Cargo.toml
  infos/Cargo.toml
  json-depth-checker/Cargo.toml
  milli/Cargo.toml
  milli/src/search/facet/facet_distribution.rs
  milli/src/update/index_documents/mod.rs
  milli/src/update/settings.rs
  milli/src/update/word_prefix_docids.rs
  milli/src/update/word_prefix_pair_proximity_docids.rs
  milli/src/update/words_prefix_position_docids.rs
  milli/tests/search/facet_distribution.rs
  milli/tests/search/mod.rs
Labels: no breaking

#524 Add benchmark on nested fields
  benchmarks/benches/indexing.rs
  benchmarks/build.rs
Labels: skip changelog, no breaking

#527 Remove the wip section part of the contributing file
  CONTRIBUTING.md
Labels: skip changelog, no breaking

#525 Simplify the error creation with thiserror
  milli/Cargo.toml
  milli/src/asc_desc.rs
  milli/src/criterion.rs
  milli/src/error.rs
Labels: skip changelog, no breaking

#526 remove useless comment
  milli/src/update/settings.rs
Labels: skip changelog, no breaking

#529 fix the mixed dataset geosearch indexing bug
  milli/src/update/index_documents/extract/extract_geo_points.rs
  milli/src/update/index_documents/mod.rs
Labels: bug, no breaking

#528 fix the searchable fields bug when a field is nested
  milli/src/index.rs
  milli/src/update/index_documents/mod.rs
  milli/src/update/settings.rs
Labels: bug, DB breaking

#530 fix the searchable fields bug when a field is nested
  milli/src/index.rs
  milli/src/update/index_documents/mod.rs
  milli/src/update/settings.rs
Labels: bug, DB breaking, API breaking

#532 Add some implementation on MatchBounds
  milli/src/search/matches/mod.rs
Labels: skip changelog, no breaking

#534 Bump milli version to v0.28.0
  benchmarks/Cargo.toml
  cli/Cargo.toml
  filter-parser/Cargo.toml
  flatten-serde-json/Cargo.toml
  helpers/Cargo.toml
  http-ui/Cargo.toml
  infos/Cargo.toml
  json-depth-checker/Cargo.toml
  milli/Cargo.toml
Labels: skip changelog, no breaking

#538 speedup exact words
  milli/src/index.rs
  milli/src/search/mod.rs
  milli/src/search/query_tree.rs
  milli/src/update/settings.rs
Labels: no breaking
