Repository meilisearch/milli, pull requests merged in 2022-11, with the labels that each got.

#659 Fix clippy error to add clippy job on Ci
  filter-parser/src/condition.rs
  filter-parser/src/lib.rs
  filter-parser/src/value.rs
  milli/src/heed_codec/facet/mod.rs
  milli/src/index.rs
  milli/src/lib.rs
  milli/src/search/criteria/asc_desc.rs
  milli/src/search/criteria/attribute.rs
  milli/src/search/criteria/mod.rs
  milli/src/search/distinct/facet_distinct.rs
  milli/src/search/distinct/mod.rs
  milli/src/search/facet/facet_distribution_iter.rs
  milli/src/search/facet/facet_range_search.rs
  milli/src/search/facet/facet_sort_ascending.rs
  milli/src/search/facet/facet_sort_descending.rs
  milli/src/search/facet/filter.rs
  milli/src/search/facet/mod.rs
  milli/src/search/matches/mod.rs
  milli/src/snapshot_tests.rs
  milli/src/update/available_documents_ids.rs
  milli/src/update/delete_documents.rs
  milli/src/update/facet/bulk.rs
  milli/src/update/facet/delete.rs
  milli/src/update/facet/incremental.rs
  milli/src/update/index_documents/extract/extract_geo_points.rs
  milli/src/update/index_documents/extract/mod.rs
  milli/src/update/index_documents/mod.rs
  milli/src/update/prefix_word_pairs/prefix_word.rs
  milli/src/update/prefix_word_pairs/word_prefix.rs
  milli/tests/search/mod.rs
  milli/tests/search/query_criteria.rs
Labels: no breaking, hacktoberfest-accepted

#673 Add clippy job
  .github/workflows/rust.yml
  bors.toml
  milli/src/search/criteria/mod.rs
  milli/src/search/criteria/proximity.rs
  milli/src/search/matches/matching_words.rs
  milli/src/search/query_tree.rs
  milli/src/update/facet/incremental.rs
  milli/src/update/index_documents/extract/extract_docid_word_positions.rs
  milli/src/update/index_documents/extract/extract_facet_string_docids.rs
  milli/src/update/index_documents/extract/extract_word_pair_proximity_docids.rs
  milli/src/update/index_documents/extract/extract_word_position_docids.rs
  milli/src/update/index_documents/transform.rs
  milli/src/update/words_prefixes_fst.rs
Labels: no breaking, maintenance, hacktoberfest-accepted

#689 Handle non-finite floats consistently in filters
  filter-parser/src/error.rs
  filter-parser/src/lib.rs
  milli/src/search/facet/filter.rs
Labels: bug, no breaking

#692 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation, skip changelog

#693 use the lmdb-master.3 branch
  milli/Cargo.toml
Labels: DB breaking

#698 Fix soft deleted bug settings
  benchmarks/Cargo.toml
  cli/Cargo.toml
  filter-parser/Cargo.toml
  flatten-serde-json/Cargo.toml
  helpers/Cargo.toml
  http-ui/Cargo.toml
  infos/Cargo.toml
  json-depth-checker/Cargo.toml
  milli/Cargo.toml
  milli/src/update/index_documents/transform.rs
  milli/src/update/settings.rs
Labels: no breaking

#699 Force vendoring of LMDB even if a system version is available
  .github/workflows/rust.yml
  milli/Cargo.toml
Labels: bug, no breaking

#685 ci: Use pre-compiled binaries for faster CI
  .github/workflows/manual_benchmarks.yml
  .github/workflows/push_benchmarks_indexing.yml
  .github/workflows/push_benchmarks_search_geo.yml
  .github/workflows/push_benchmarks_search_songs.yml
  .github/workflows/push_benchmarks_search_wiki.yml
  .github/workflows/update-cargo-toml-version.yml
Labels: no breaking, maintenance

#696 Fix Facet Indexing bugs
  milli/src/update/facet/bulk.rs
  milli/src/update/facet/incremental.rs
  milli/src/update/index_documents/extract/extract_facet_number_docids.rs
  milli/src/update/index_documents/extract/extract_facet_string_docids.rs
  milli/src/update/index_documents/extract/extract_fid_docid_facet_values.rs
  milli/src/update/index_documents/helpers/mod.rs
  milli/src/update/index_documents/mod.rs
Labels: bug, no breaking

#697 Fix bug in prefix DB indexing
  milli/src/update/prefix_word_pairs/mod.rs
  milli/src/update/prefix_word_pairs/snapshots/mod.rs/test_batch_bug_3043/prefix_word_pair_proximity_docids.snap
  milli/src/update/prefix_word_pairs/snapshots/mod.rs/test_batch_bug_3043/word_pair_proximity_docids.snap
  milli/src/update/prefix_word_pairs/snapshots/mod.rs/test_batch_bug_3043/word_prefix_pair_proximity_docids.snap
  milli/src/update/prefix_word_pairs/word_prefix.rs
Labels: bug, no breaking

#710 Update Clippy to use Rust Stable
  .github/workflows/rust.yml
Labels: skip changelog, no breaking

#707 Add all_obkv_to_json function
  milli/src/lib.rs
Labels: no breaking

#711 Replace deprecated gh actions
  .github/workflows/manual_benchmarks.yml
  .github/workflows/push_benchmarks_indexing.yml
  .github/workflows/push_benchmarks_search_geo.yml
  .github/workflows/push_benchmarks_search_songs.yml
  .github/workflows/push_benchmarks_search_wiki.yml
Labels: maintenance

#712 Fix bulk facet indexing bug
  milli/src/update/facet/bulk.rs
  milli/src/update/facet/incremental.rs
Labels: bug, no breaking

#708 Reduce memory usage of the MatchingWords structure
  benchmarks/benches/formatting.rs
  milli/src/lib.rs
  milli/src/search/matches/matching_words.rs
  milli/src/search/matches/mod.rs
  milli/src/search/query_tree.rs
  milli/src/update/index_documents/extract/extract_docid_word_positions.rs
  milli/src/update/index_documents/extract/extract_facet_string_docids.rs
  milli/src/update/index_documents/extract/extract_fid_docid_facet_values.rs
  milli/src/update/index_documents/helpers/mod.rs
Labels: no breaking, performance
