Repository meilisearch/milli, pull requests merged in 2023-01, with the labels that each got.

#752 Simplify primary key inference
  milli/src/error.rs
  milli/src/update/index_documents/enrich.rs
  milli/src/update/index_documents/mod.rs
  milli/src/update/index_documents/transform.rs
Labels: indexing, DB breaking, API breaking

#709 Optimise the `ExactWords` sub-criterion within `Exactness`
  milli/src/search/criteria/exactness.rs
Labels: no breaking, performance

#736 Update charabia
  milli/Cargo.toml
  milli/src/search/matches/mod.rs
  milli/src/search/query_tree.rs
  milli/src/update/index_documents/mod.rs
Labels: DB breaking

#732 Interpret synonyms as phrases
  milli/src/search/query_tree.rs
Labels: no breaking, performance

#733 Avoid a prefix-related worst-case scenario in the proximity criterion
  milli/src/search/criteria/mod.rs
  milli/src/search/criteria/proximity.rs
  milli/src/update/mod.rs
  milli/src/update/prefix_word_pairs/mod.rs
Labels: no breaking, performance

#760 Add Index::map_size
  milli/src/index.rs
Labels: no breaking

#759 Change primary key inference error messages
  milli/src/error.rs
Labels: documentation, skip changelog, no breaking

#761 Integrate deserr
  benchmarks/benches/utils.rs
  cli/src/main.rs
  milli/Cargo.toml
  milli/src/search/criteria/asc_desc.rs
  milli/src/search/criteria/exactness.rs
  milli/src/search/criteria/proximity.rs
  milli/src/update/settings.rs
  milli/tests/search/mod.rs
  milli/tests/search/query_criteria.rs
Labels: API breaking, maintenance

#764 Update deserr to latest version
  milli/Cargo.toml
  milli/src/update/settings.rs
Labels: no breaking

#766 Indicate filterable attributes when the user sets a non filterable attribute in facet distributions
  milli/src/error.rs
  milli/src/search/facet/facet_distribution.rs
Labels: no breaking

#763 Fixes error message when lat and lng are unparseable
  milli/src/index.rs
  milli/src/snapshots/index.rs/bug_3007/geo_faceted_documents_ids.snap
  milli/src/update/index_documents/enrich.rs
  milli/src/update/index_documents/mod.rs
Labels: API breaking

#770 Update deserr v0.3.0
  milli/Cargo.toml
Labels: no breaking

#772 Throw an error on unknown fields specified in the _geo field
  milli/src/error.rs
  milli/src/index.rs
  milli/src/snapshots/index.rs/unexpected_extra_fields_in_geo_field/geo_faceted_documents_ids.snap
  milli/src/update/index_documents/enrich.rs
Labels: bug, API breaking

#769 Modify README to prevent contributions
  README.md
Labels: documentation, skip changelog

#775 Fix clippy for Rust 1.67, allow `uninlined_format_args`
  .github/workflows/rust.yml
  milli/src/index.rs
  milli/src/search/criteria/proximity.rs
  milli/src/search/criteria/typo.rs
  milli/src/update/delete_documents.rs
  milli/src/update/facet/incremental.rs
  milli/src/update/index_documents/helpers/grenad_helpers.rs
  milli/src/update/index_documents/transform.rs
  milli/tests/search/phrase_search.rs
Labels: no breaking

#776 Reduce incremental indexing time of `words_prefix_position_docids` DB
  milli/src/update/words_prefix_position_docids.rs
Labels: no breaking, performance
